updated frontend
RageMpOpenSource/RAGE-Accounts pull request #4
Opened 2021-01-20 21:56 UTC by aksiere

2021-01-20 22:15 UTC, MrPancakers commented on client_packages/cef/login/index.html
> +		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="
I see you've replaced the local files for CDN links, is there a reason why you choose to use external resources? Using external files can add additional loading time onto users which is why CDN's are avoided in this resource.

Also, we already use bootstrap v4.5 and this is v4.

As of now, I wouldn't merge this with CDN links, I'd want these to be local files (see the cef/assets folder)

2021-01-20 22:19 UTC, MrPancakers requested changes
CDN links aren't necessary here, if you want to update the jQuery resource you can. Otherwise, revert those changes and I can test it out and merge if all works out.

2021-01-22 22:58 UTC, MrPancakers requested changes
Not sure why but after all your changes the pages don't even work in-game anymore. I cannot submit anything so this needs to be looked into. Try testing in-game before submitting changes, I can try debug later but for now I still cannot merge this.

2021-01-31 01:16 UTC, aksiere commented
refactored.
should work

2021-02-05 01:41 UTC, MrPancakers approved these changes

2021-02-05 01:41 UTC, MrPancakers commented
> refactored.
> it works for me

Awesome tested again and it's all working, just need to fix up the error messages as they aren't user friendly but once I've done that I'll merge it. Thanks

2021-02-05 02:03 UTC, merged